In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy as scp

from ucimlrepo import fetch_ucirepo

In [2]:
wine = fetch_ucirepo(id = 109)

In [3]:
wine_df = pd.concat([wine['data']['features'], wine['data']['targets']], axis = 1)
display(wine_df)

Alcohol  Malicacid   Ash  Alcalinity_of_ash  Magnesium  Total_phenols  \
0      14.23       1.71  2.43               15.6        127           2.80   
1      13.20       1.78  2.14               11.2        100           2.65   
2      13.16       2.36  2.67               18.6        101           2.80   
3      14.37       1.95  2.50               16.8        113           3.85   
4      13.24       2.59  2.87               21.0        118           2.80   
..       ...        ...   ...                ...        ...            ...   
173    13.71       5.65  2.45               20.5         95           1.68   
174    13.40       3.91  2.48               23.0        102           1.80   
175    13.27       4.28  2.26               20.0        120           1.59   
176    13.17       2.59  2.37               20.0        120           1.65   
177    14.13       4.10  2.74               24.5         96           2.05   

     Flavanoids  Nonflavanoid_phenols  Proanthocyanins  Color_intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     0D280_0D315_of_diluted_wines  Proline  class  
0                            3.92     1065      1  
1                            3.40     1050      1  
2                            3.17     1185      1  
3                            3.45     1480      1  
4                            2.93      735      1  
..                            ...      ...    ...  
173                          1.74      740      3  
174                          1.56      750      3  
175                          1.56      835      3  
176                          1.62      840      3  
177                          1.60      560      3  

[178 rows x 14 columns]

weights and biases are joined within one matrix

In [4]:
# testing concat by columns
test_weights = torch.ones((4, 5))
display(test_weights)
test_biases = torch.zeros((4, 1))
display(test_biases)
test_concat = torch.concat([test_weights, test_biases], dim = 1)
display(test_concat)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

tensor([[0.],
        [0.],
        [0.],
        [0.]])

tensor([[1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 0.]])

In [5]:
# testing concat by rows
test_weights = torch.ones((3, 4))
display(test_weights)
test_biases = torch.zeros((2, 4))
display(test_biases)
test_concat = torch.concat([test_weights, test_biases], dim = 0)
display(test_concat)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
# testing stack by rows
test_weights = torch.ones((3, 4))
display(test_weights)
test_biases = torch.zeros((3, 4))
display(test_biases)
test_concat = torch.stack([test_weights, test_biases], dim = 0)
test_concat2 = torch.stack([test_weights, test_biases], dim = 2)
display(test_concat)
display(test_concat2)
display(test_concat2.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.]]])

torch.Size([3, 4, 2])

In [7]:
# testing matrix multiplication in pytorch

# assume 50 samples, 12 features and we include a bias term
X = torch.randn((50, 12))
bias_ones = torch.ones((X.shape[0], 1))

W = torch.randn((X.shape[1] + 1, 1))
X_aug = torch.concat([bias_ones, X], dim = 1)

display(X_aug.shape)
display(X_aug[:, 0])

y = X_aug @ W
display(y.shape)


torch.Size([50, 13])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

torch.Size([50, 1])

In [8]:
# def l2_loss(y_hat, y):
#     loss = torch.sum((y_hat - y)**2)
#     return loss

def l1_loss(y_hat, y):
    loss = torch.sum(torch.abs(y_hat - y))
    # print(loss)
    return loss

In [15]:
y1 = torch.ones((5, 1))
y2 = torch.ones((5, 1)) * 3

# display(torch.sum(y2))
l1_loss(y1, y2)
display(torch.mean(y1))

yn = torch.normal(3., 1., (4, 5))
display(yn)
display(torch.mean(yn, dim = 0))

tensor(1.)

tensor([[2.0998, 2.6081, 2.1924, 3.2629, 2.2153],
        [2.4403, 1.4220, 3.6794, 1.8607, 3.8025],
        [1.9022, 2.4286, 4.1610, 3.1501, 0.9110],
        [2.8524, 2.6757, 4.4514, 2.9013, 2.1566]])

tensor([2.3237, 2.2836, 3.6211, 2.7937, 2.2714])

In [ ]:
class LinearRegression:
    def __init__(self, num_features, num_classes, loss_fn):
        self.num_features = num_features
        self.num_classes = num_classes
        self.loss_fn = loss_fn

        self.init_weights()

    def init_weights(self):
        self.W = torch.normal(0, 0.01, (self.num_features, self.num_classes), dtype = torch.float64)
        self.b = torch.zeros(self.num_classes, dtype = torch.float64)       # could try an array of biases to see if it helps

    def fit(self, X, y, epochs = 1000, lr = 0.01, ):
        # enforce right dimensions
        assert X.shape[1] == self.num_features and y.shape[1] == self.num_classes
        
        # computes the gradient descent version of linear regression
        for t in range(epochs):
            y_hat = self.forward(X)
            loss = self.loss_fn(X, y)

            # compute gradient
            dW = (2/X.shape[0]) * (X.T @ (y - y_hat))
            db = (2/X.shape[0]) * torch.sum(y - y_hat)

            # update features
            self.W = self.W - (lr * dW)
            self.b = self.b - (lr * db)


    def fit_OLS(self, X, y):
        assert X.shape[1] == self.num_features and y.shape[1] == self.num_classes

        # compute OLS solution
        W_OLS = torch.inverse(X.T @ X) @ X.T @ y
        b_OLS = torch.mean(y) - torch.mean(X @ W)
        self.W = W_OLS
        self.b = b_OLS

    def __call__(self, X):
        return self.forward(X)

    def forward(self, X):
        # assert X is of the shape (num_inputs, num_features)
        assert X.shape[1] == self.num_features
        return (X @ self.W) + self.b
    
    def predict_proba(self, X_val):
        if self.num_classes == 1:
            # perform binary classification
        else:
            # perform multiclassification
        pass

    def predict(self, X_val):
        # also split into 2 cases for binary- and multi- classification

        pass
    

SyntaxError: invalid syntax (3653445817.py, line 2)